server:
  port: 7201
spring: 
  rabbitmq:     # 现在将集成RabbitMQ作为消息服务总线处理
    host: rabbitmq-server   # RabbitMQ主机服务地址
    port: 5672    # RabbitMQ的监听端口
    username: mldnjava  # 用户名
    password: hello # 密码
  application:
    name: microcloud-config
  cloud:  # 进行SpringCloud的相关配置
    bus:
      trace:
        enabled: true
    config: # 进行SpringCloudConfig的相关配置
      server: # 设置服务的连接地址
        git:  # 本次使用的是GIT作为仓库的管理，所以需要设置GIT的连接地址
          uri: git@github.com:mldn/microconfig    # 为公共仓库信息，如果某些信息找不到了就使用它
          search-paths:
          - microcloud-*

eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-config.com:7301/eureka
  instance:
    prefer-ip-address: true     # 在地址栏上使用IP地址进行显示
    instance-id: config-7201.com
        
encrypt:
  keyStore:
    location: classpath:/server.jks   # server.jks的配置文件的路径
    password: mldnjava      # 设置store的密码 
    alias: mytestkey
    secret: changeit      # keypass密码