server:
  port: 7101
spring: 
  application:
    name: microcloud-config
  cloud:  # 进行SpringCloud的相关配置
    config: # 进行SpringCloudConfig的相关配置
      server: # 设置服务的连接地址
        git:  # 本次使用的是GIT作为仓库的管理，所以需要设置GIT的连接地址
          uri: git@github.com:mldn/microconfig    # 为公共仓库信息，如果某些信息找不到了就使用它
          search-paths:
          - microcloud-*
          
encrypt:
  key: mldnjava.cn    # 设置了一个加密的访问密钥